import type { Metadata } from "next";
import { Inter, Yeseva_One } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter"});

const yesevaOne = Yeseva_One({ weight: "400", variable: "--font-yeseva", subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="text-yeseva">
      <body className={`${yesevaOne.variable} ${inter.variable}`}>{children}</body>
    </html>
  );
}
